// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smarthomecommand.proto

package org.gmagnotta.smarthome.model.event;

public final class Smarthomecommand {
  private Smarthomecommand() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SmartHomeCommandRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.gmagnotta.smarthome.model.event.SmartHomeCommandRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>required string replyto = 2;</code>
     * @return Whether the replyto field is set.
     */
    boolean hasReplyto();
    /**
     * <code>required string replyto = 2;</code>
     * @return The replyto.
     */
    java.lang.String getReplyto();
    /**
     * <code>required string replyto = 2;</code>
     * @return The bytes for replyto.
     */
    com.google.protobuf.ByteString
        getReplytoBytes();

    /**
     * <code>required string realm = 3;</code>
     * @return Whether the realm field is set.
     */
    boolean hasRealm();
    /**
     * <code>required string realm = 3;</code>
     * @return The realm.
     */
    java.lang.String getRealm();
    /**
     * <code>required string realm = 3;</code>
     * @return The bytes for realm.
     */
    com.google.protobuf.ByteString
        getRealmBytes();

    /**
     * <code>required .org.gmagnotta.smarthome.model.event.SmartHomeCommandRequest.Operation operation = 4;</code>
     * @return Whether the operation field is set.
     */
    boolean hasOperation();
    /**
     * <code>required .org.gmagnotta.smarthome.model.event.SmartHomeCommandRequest.Operation operation = 4;</code>
     * @return The operation.
     */
    org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest.Operation getOperation();

    /**
     * <code>required string resource = 5;</code>
     * @return Whether the resource field is set.
     */
    boolean hasResource();
    /**
     * <code>required string resource = 5;</code>
     * @return The resource.
     */
    java.lang.String getResource();
    /**
     * <code>required string resource = 5;</code>
     * @return The bytes for resource.
     */
    com.google.protobuf.ByteString
        getResourceBytes();

    /**
     * <code>required string type = 6;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>required string type = 6;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <code>required string type = 6;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>required string value = 7;</code>
     * @return Whether the value field is set.
     */
    boolean hasValue();
    /**
     * <code>required string value = 7;</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>required string value = 7;</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code org.gmagnotta.smarthome.model.event.SmartHomeCommandRequest}
   */
  public static final class SmartHomeCommandRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.gmagnotta.smarthome.model.event.SmartHomeCommandRequest)
      SmartHomeCommandRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SmartHomeCommandRequest.newBuilder() to construct.
    private SmartHomeCommandRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SmartHomeCommandRequest() {
      id_ = "";
      replyto_ = "";
      realm_ = "";
      operation_ = 0;
      resource_ = "";
      type_ = "";
      value_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SmartHomeCommandRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SmartHomeCommandRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              replyto_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              realm_ = bs;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest.Operation value = org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest.Operation.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                operation_ = rawValue;
              }
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              resource_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              type_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              value_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.gmagnotta.smarthome.model.event.Smarthomecommand.internal_static_org_gmagnotta_smarthome_model_event_SmartHomeCommandRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.gmagnotta.smarthome.model.event.Smarthomecommand.internal_static_org_gmagnotta_smarthome_model_event_SmartHomeCommandRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest.class, org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest.Builder.class);
    }

    /**
     * Protobuf enum {@code org.gmagnotta.smarthome.model.event.SmartHomeCommandRequest.Operation}
     */
    public enum Operation
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CREATE = 0;</code>
       */
      CREATE(0),
      /**
       * <code>READ = 1;</code>
       */
      READ(1),
      /**
       * <code>UPDATE = 2;</code>
       */
      UPDATE(2),
      /**
       * <code>DELETE = 3;</code>
       */
      DELETE(3),
      ;

      /**
       * <code>CREATE = 0;</code>
       */
      public static final int CREATE_VALUE = 0;
      /**
       * <code>READ = 1;</code>
       */
      public static final int READ_VALUE = 1;
      /**
       * <code>UPDATE = 2;</code>
       */
      public static final int UPDATE_VALUE = 2;
      /**
       * <code>DELETE = 3;</code>
       */
      public static final int DELETE_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Operation valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Operation forNumber(int value) {
        switch (value) {
          case 0: return CREATE;
          case 1: return READ;
          case 2: return UPDATE;
          case 3: return DELETE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Operation>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Operation> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Operation>() {
              public Operation findValueByNumber(int number) {
                return Operation.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final Operation[] VALUES = values();

      public static Operation valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Operation(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.gmagnotta.smarthome.model.event.SmartHomeCommandRequest.Operation)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REPLYTO_FIELD_NUMBER = 2;
    private volatile java.lang.Object replyto_;
    /**
     * <code>required string replyto = 2;</code>
     * @return Whether the replyto field is set.
     */
    @java.lang.Override
    public boolean hasReplyto() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string replyto = 2;</code>
     * @return The replyto.
     */
    @java.lang.Override
    public java.lang.String getReplyto() {
      java.lang.Object ref = replyto_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          replyto_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string replyto = 2;</code>
     * @return The bytes for replyto.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReplytoBytes() {
      java.lang.Object ref = replyto_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        replyto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REALM_FIELD_NUMBER = 3;
    private volatile java.lang.Object realm_;
    /**
     * <code>required string realm = 3;</code>
     * @return Whether the realm field is set.
     */
    @java.lang.Override
    public boolean hasRealm() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string realm = 3;</code>
     * @return The realm.
     */
    @java.lang.Override
    public java.lang.String getRealm() {
      java.lang.Object ref = realm_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          realm_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string realm = 3;</code>
     * @return The bytes for realm.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRealmBytes() {
      java.lang.Object ref = realm_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        realm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPERATION_FIELD_NUMBER = 4;
    private int operation_;
    /**
     * <code>required .org.gmagnotta.smarthome.model.event.SmartHomeCommandRequest.Operation operation = 4;</code>
     * @return Whether the operation field is set.
     */
    @java.lang.Override public boolean hasOperation() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required .org.gmagnotta.smarthome.model.event.SmartHomeCommandRequest.Operation operation = 4;</code>
     * @return The operation.
     */
    @java.lang.Override public org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest.Operation getOperation() {
      @SuppressWarnings("deprecation")
      org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest.Operation result = org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest.Operation.valueOf(operation_);
      return result == null ? org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest.Operation.CREATE : result;
    }

    public static final int RESOURCE_FIELD_NUMBER = 5;
    private volatile java.lang.Object resource_;
    /**
     * <code>required string resource = 5;</code>
     * @return Whether the resource field is set.
     */
    @java.lang.Override
    public boolean hasResource() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required string resource = 5;</code>
     * @return The resource.
     */
    @java.lang.Override
    public java.lang.String getResource() {
      java.lang.Object ref = resource_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          resource_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string resource = 5;</code>
     * @return The bytes for resource.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResourceBytes() {
      java.lang.Object ref = resource_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 6;
    private volatile java.lang.Object type_;
    /**
     * <code>required string type = 6;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override
    public boolean hasType() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required string type = 6;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 6;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 7;
    private volatile java.lang.Object value_;
    /**
     * <code>required string value = 7;</code>
     * @return Whether the value field is set.
     */
    @java.lang.Override
    public boolean hasValue() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>required string value = 7;</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string value = 7;</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReplyto()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRealm()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOperation()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResource()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, replyto_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, realm_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeEnum(4, operation_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, resource_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, type_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, replyto_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, realm_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, operation_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, resource_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, type_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest)) {
        return super.equals(obj);
      }
      org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest other = (org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (!getId()
            .equals(other.getId())) return false;
      }
      if (hasReplyto() != other.hasReplyto()) return false;
      if (hasReplyto()) {
        if (!getReplyto()
            .equals(other.getReplyto())) return false;
      }
      if (hasRealm() != other.hasRealm()) return false;
      if (hasRealm()) {
        if (!getRealm()
            .equals(other.getRealm())) return false;
      }
      if (hasOperation() != other.hasOperation()) return false;
      if (hasOperation()) {
        if (operation_ != other.operation_) return false;
      }
      if (hasResource() != other.hasResource()) return false;
      if (hasResource()) {
        if (!getResource()
            .equals(other.getResource())) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (!getType()
            .equals(other.getType())) return false;
      }
      if (hasValue() != other.hasValue()) return false;
      if (hasValue()) {
        if (!getValue()
            .equals(other.getValue())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasReplyto()) {
        hash = (37 * hash) + REPLYTO_FIELD_NUMBER;
        hash = (53 * hash) + getReplyto().hashCode();
      }
      if (hasRealm()) {
        hash = (37 * hash) + REALM_FIELD_NUMBER;
        hash = (53 * hash) + getRealm().hashCode();
      }
      if (hasOperation()) {
        hash = (37 * hash) + OPERATION_FIELD_NUMBER;
        hash = (53 * hash) + operation_;
      }
      if (hasResource()) {
        hash = (37 * hash) + RESOURCE_FIELD_NUMBER;
        hash = (53 * hash) + getResource().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
      }
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.gmagnotta.smarthome.model.event.SmartHomeCommandRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.gmagnotta.smarthome.model.event.SmartHomeCommandRequest)
        org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.gmagnotta.smarthome.model.event.Smarthomecommand.internal_static_org_gmagnotta_smarthome_model_event_SmartHomeCommandRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.gmagnotta.smarthome.model.event.Smarthomecommand.internal_static_org_gmagnotta_smarthome_model_event_SmartHomeCommandRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest.class, org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest.Builder.class);
      }

      // Construct using org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        replyto_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        realm_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        operation_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        resource_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.gmagnotta.smarthome.model.event.Smarthomecommand.internal_static_org_gmagnotta_smarthome_model_event_SmartHomeCommandRequest_descriptor;
      }

      @java.lang.Override
      public org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest getDefaultInstanceForType() {
        return org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest build() {
        org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest buildPartial() {
        org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest result = new org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.replyto_ = replyto_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.realm_ = realm_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.operation_ = operation_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.resource_ = resource_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          to_bitField0_ |= 0x00000040;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest) {
          return mergeFrom((org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest other) {
        if (other == org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasReplyto()) {
          bitField0_ |= 0x00000002;
          replyto_ = other.replyto_;
          onChanged();
        }
        if (other.hasRealm()) {
          bitField0_ |= 0x00000004;
          realm_ = other.realm_;
          onChanged();
        }
        if (other.hasOperation()) {
          setOperation(other.getOperation());
        }
        if (other.hasResource()) {
          bitField0_ |= 0x00000010;
          resource_ = other.resource_;
          onChanged();
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000020;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000040;
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasReplyto()) {
          return false;
        }
        if (!hasRealm()) {
          return false;
        }
        if (!hasOperation()) {
          return false;
        }
        if (!hasResource()) {
          return false;
        }
        if (!hasType()) {
          return false;
        }
        if (!hasValue()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       * @return Whether the id field is set.
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object replyto_ = "";
      /**
       * <code>required string replyto = 2;</code>
       * @return Whether the replyto field is set.
       */
      public boolean hasReplyto() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string replyto = 2;</code>
       * @return The replyto.
       */
      public java.lang.String getReplyto() {
        java.lang.Object ref = replyto_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            replyto_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string replyto = 2;</code>
       * @return The bytes for replyto.
       */
      public com.google.protobuf.ByteString
          getReplytoBytes() {
        java.lang.Object ref = replyto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          replyto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string replyto = 2;</code>
       * @param value The replyto to set.
       * @return This builder for chaining.
       */
      public Builder setReplyto(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        replyto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string replyto = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearReplyto() {
        bitField0_ = (bitField0_ & ~0x00000002);
        replyto_ = getDefaultInstance().getReplyto();
        onChanged();
        return this;
      }
      /**
       * <code>required string replyto = 2;</code>
       * @param value The bytes for replyto to set.
       * @return This builder for chaining.
       */
      public Builder setReplytoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        replyto_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object realm_ = "";
      /**
       * <code>required string realm = 3;</code>
       * @return Whether the realm field is set.
       */
      public boolean hasRealm() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required string realm = 3;</code>
       * @return The realm.
       */
      public java.lang.String getRealm() {
        java.lang.Object ref = realm_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            realm_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string realm = 3;</code>
       * @return The bytes for realm.
       */
      public com.google.protobuf.ByteString
          getRealmBytes() {
        java.lang.Object ref = realm_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          realm_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string realm = 3;</code>
       * @param value The realm to set.
       * @return This builder for chaining.
       */
      public Builder setRealm(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        realm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string realm = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRealm() {
        bitField0_ = (bitField0_ & ~0x00000004);
        realm_ = getDefaultInstance().getRealm();
        onChanged();
        return this;
      }
      /**
       * <code>required string realm = 3;</code>
       * @param value The bytes for realm to set.
       * @return This builder for chaining.
       */
      public Builder setRealmBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        realm_ = value;
        onChanged();
        return this;
      }

      private int operation_ = 0;
      /**
       * <code>required .org.gmagnotta.smarthome.model.event.SmartHomeCommandRequest.Operation operation = 4;</code>
       * @return Whether the operation field is set.
       */
      @java.lang.Override public boolean hasOperation() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required .org.gmagnotta.smarthome.model.event.SmartHomeCommandRequest.Operation operation = 4;</code>
       * @return The operation.
       */
      @java.lang.Override
      public org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest.Operation getOperation() {
        @SuppressWarnings("deprecation")
        org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest.Operation result = org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest.Operation.valueOf(operation_);
        return result == null ? org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest.Operation.CREATE : result;
      }
      /**
       * <code>required .org.gmagnotta.smarthome.model.event.SmartHomeCommandRequest.Operation operation = 4;</code>
       * @param value The operation to set.
       * @return This builder for chaining.
       */
      public Builder setOperation(org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest.Operation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        operation_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .org.gmagnotta.smarthome.model.event.SmartHomeCommandRequest.Operation operation = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperation() {
        bitField0_ = (bitField0_ & ~0x00000008);
        operation_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object resource_ = "";
      /**
       * <code>required string resource = 5;</code>
       * @return Whether the resource field is set.
       */
      public boolean hasResource() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required string resource = 5;</code>
       * @return The resource.
       */
      public java.lang.String getResource() {
        java.lang.Object ref = resource_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            resource_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string resource = 5;</code>
       * @return The bytes for resource.
       */
      public com.google.protobuf.ByteString
          getResourceBytes() {
        java.lang.Object ref = resource_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resource_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string resource = 5;</code>
       * @param value The resource to set.
       * @return This builder for chaining.
       */
      public Builder setResource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        resource_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string resource = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearResource() {
        bitField0_ = (bitField0_ & ~0x00000010);
        resource_ = getDefaultInstance().getResource();
        onChanged();
        return this;
      }
      /**
       * <code>required string resource = 5;</code>
       * @param value The bytes for resource to set.
       * @return This builder for chaining.
       */
      public Builder setResourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        resource_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 6;</code>
       * @return Whether the type field is set.
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>required string type = 6;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 6;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 6;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 6;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        type_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>required string value = 7;</code>
       * @return Whether the value field is set.
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>required string value = 7;</code>
       * @return The value.
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string value = 7;</code>
       * @return The bytes for value.
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string value = 7;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000040);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 7;</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        value_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.gmagnotta.smarthome.model.event.SmartHomeCommandRequest)
    }

    // @@protoc_insertion_point(class_scope:org.gmagnotta.smarthome.model.event.SmartHomeCommandRequest)
    private static final org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest();
    }

    public static org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SmartHomeCommandRequest>
        PARSER = new com.google.protobuf.AbstractParser<SmartHomeCommandRequest>() {
      @java.lang.Override
      public SmartHomeCommandRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SmartHomeCommandRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SmartHomeCommandRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SmartHomeCommandRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SmartHomeCommandResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.gmagnotta.smarthome.model.event.SmartHomeCommandResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string correlationid = 1;</code>
     * @return Whether the correlationid field is set.
     */
    boolean hasCorrelationid();
    /**
     * <code>required string correlationid = 1;</code>
     * @return The correlationid.
     */
    java.lang.String getCorrelationid();
    /**
     * <code>required string correlationid = 1;</code>
     * @return The bytes for correlationid.
     */
    com.google.protobuf.ByteString
        getCorrelationidBytes();

    /**
     * <code>required string status = 2;</code>
     * @return Whether the status field is set.
     */
    boolean hasStatus();
    /**
     * <code>required string status = 2;</code>
     * @return The status.
     */
    java.lang.String getStatus();
    /**
     * <code>required string status = 2;</code>
     * @return The bytes for status.
     */
    com.google.protobuf.ByteString
        getStatusBytes();

    /**
     * <code>optional string description = 3;</code>
     * @return Whether the description field is set.
     */
    boolean hasDescription();
    /**
     * <code>optional string description = 3;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>optional string description = 3;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();
  }
  /**
   * Protobuf type {@code org.gmagnotta.smarthome.model.event.SmartHomeCommandResponse}
   */
  public static final class SmartHomeCommandResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.gmagnotta.smarthome.model.event.SmartHomeCommandResponse)
      SmartHomeCommandResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SmartHomeCommandResponse.newBuilder() to construct.
    private SmartHomeCommandResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SmartHomeCommandResponse() {
      correlationid_ = "";
      status_ = "";
      description_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SmartHomeCommandResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SmartHomeCommandResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              correlationid_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              status_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              description_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.gmagnotta.smarthome.model.event.Smarthomecommand.internal_static_org_gmagnotta_smarthome_model_event_SmartHomeCommandResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.gmagnotta.smarthome.model.event.Smarthomecommand.internal_static_org_gmagnotta_smarthome_model_event_SmartHomeCommandResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse.class, org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse.Builder.class);
    }

    private int bitField0_;
    public static final int CORRELATIONID_FIELD_NUMBER = 1;
    private volatile java.lang.Object correlationid_;
    /**
     * <code>required string correlationid = 1;</code>
     * @return Whether the correlationid field is set.
     */
    @java.lang.Override
    public boolean hasCorrelationid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string correlationid = 1;</code>
     * @return The correlationid.
     */
    @java.lang.Override
    public java.lang.String getCorrelationid() {
      java.lang.Object ref = correlationid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          correlationid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string correlationid = 1;</code>
     * @return The bytes for correlationid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCorrelationidBytes() {
      java.lang.Object ref = correlationid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        correlationid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private volatile java.lang.Object status_;
    /**
     * <code>required string status = 2;</code>
     * @return Whether the status field is set.
     */
    @java.lang.Override
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string status = 2;</code>
     * @return The status.
     */
    @java.lang.Override
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          status_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string status = 2;</code>
     * @return The bytes for status.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private volatile java.lang.Object description_;
    /**
     * <code>optional string description = 3;</code>
     * @return Whether the description field is set.
     */
    @java.lang.Override
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string description = 3;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string description = 3;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCorrelationid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, correlationid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, status_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, correlationid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, status_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse)) {
        return super.equals(obj);
      }
      org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse other = (org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse) obj;

      if (hasCorrelationid() != other.hasCorrelationid()) return false;
      if (hasCorrelationid()) {
        if (!getCorrelationid()
            .equals(other.getCorrelationid())) return false;
      }
      if (hasStatus() != other.hasStatus()) return false;
      if (hasStatus()) {
        if (!getStatus()
            .equals(other.getStatus())) return false;
      }
      if (hasDescription() != other.hasDescription()) return false;
      if (hasDescription()) {
        if (!getDescription()
            .equals(other.getDescription())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCorrelationid()) {
        hash = (37 * hash) + CORRELATIONID_FIELD_NUMBER;
        hash = (53 * hash) + getCorrelationid().hashCode();
      }
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus().hashCode();
      }
      if (hasDescription()) {
        hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
        hash = (53 * hash) + getDescription().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.gmagnotta.smarthome.model.event.SmartHomeCommandResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.gmagnotta.smarthome.model.event.SmartHomeCommandResponse)
        org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.gmagnotta.smarthome.model.event.Smarthomecommand.internal_static_org_gmagnotta_smarthome_model_event_SmartHomeCommandResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.gmagnotta.smarthome.model.event.Smarthomecommand.internal_static_org_gmagnotta_smarthome_model_event_SmartHomeCommandResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse.class, org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse.Builder.class);
      }

      // Construct using org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        correlationid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.gmagnotta.smarthome.model.event.Smarthomecommand.internal_static_org_gmagnotta_smarthome_model_event_SmartHomeCommandResponse_descriptor;
      }

      @java.lang.Override
      public org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse getDefaultInstanceForType() {
        return org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse build() {
        org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse buildPartial() {
        org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse result = new org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.correlationid_ = correlationid_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.description_ = description_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse) {
          return mergeFrom((org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse other) {
        if (other == org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse.getDefaultInstance()) return this;
        if (other.hasCorrelationid()) {
          bitField0_ |= 0x00000001;
          correlationid_ = other.correlationid_;
          onChanged();
        }
        if (other.hasStatus()) {
          bitField0_ |= 0x00000002;
          status_ = other.status_;
          onChanged();
        }
        if (other.hasDescription()) {
          bitField0_ |= 0x00000004;
          description_ = other.description_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasCorrelationid()) {
          return false;
        }
        if (!hasStatus()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object correlationid_ = "";
      /**
       * <code>required string correlationid = 1;</code>
       * @return Whether the correlationid field is set.
       */
      public boolean hasCorrelationid() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string correlationid = 1;</code>
       * @return The correlationid.
       */
      public java.lang.String getCorrelationid() {
        java.lang.Object ref = correlationid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            correlationid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string correlationid = 1;</code>
       * @return The bytes for correlationid.
       */
      public com.google.protobuf.ByteString
          getCorrelationidBytes() {
        java.lang.Object ref = correlationid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          correlationid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string correlationid = 1;</code>
       * @param value The correlationid to set.
       * @return This builder for chaining.
       */
      public Builder setCorrelationid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        correlationid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string correlationid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCorrelationid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        correlationid_ = getDefaultInstance().getCorrelationid();
        onChanged();
        return this;
      }
      /**
       * <code>required string correlationid = 1;</code>
       * @param value The bytes for correlationid to set.
       * @return This builder for chaining.
       */
      public Builder setCorrelationidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        correlationid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object status_ = "";
      /**
       * <code>required string status = 2;</code>
       * @return Whether the status field is set.
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string status = 2;</code>
       * @return The status.
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            status_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string status = 2;</code>
       * @return The bytes for status.
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string status = 2;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string status = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <code>required string status = 2;</code>
       * @param value The bytes for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>optional string description = 3;</code>
       * @return Whether the description field is set.
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string description = 3;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            description_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string description = 3;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string description = 3;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000004);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 3;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        description_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.gmagnotta.smarthome.model.event.SmartHomeCommandResponse)
    }

    // @@protoc_insertion_point(class_scope:org.gmagnotta.smarthome.model.event.SmartHomeCommandResponse)
    private static final org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse();
    }

    public static org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SmartHomeCommandResponse>
        PARSER = new com.google.protobuf.AbstractParser<SmartHomeCommandResponse>() {
      @java.lang.Override
      public SmartHomeCommandResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SmartHomeCommandResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SmartHomeCommandResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SmartHomeCommandResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.gmagnotta.smarthome.model.event.Smarthomecommand.SmartHomeCommandResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_gmagnotta_smarthome_model_event_SmartHomeCommandRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_gmagnotta_smarthome_model_event_SmartHomeCommandRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_gmagnotta_smarthome_model_event_SmartHomeCommandResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_gmagnotta_smarthome_model_event_SmartHomeCommandResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026smarthomecommand.proto\022#org.gmagnotta." +
      "smarthome.model.event\"\212\002\n\027SmartHomeComma" +
      "ndRequest\022\n\n\002id\030\001 \002(\t\022\017\n\007replyto\030\002 \002(\t\022\r" +
      "\n\005realm\030\003 \002(\t\022Y\n\toperation\030\004 \002(\0162F.org.g" +
      "magnotta.smarthome.model.event.SmartHome" +
      "CommandRequest.Operation\022\020\n\010resource\030\005 \002" +
      "(\t\022\014\n\004type\030\006 \002(\t\022\r\n\005value\030\007 \002(\t\"9\n\tOpera" +
      "tion\022\n\n\006CREATE\020\000\022\010\n\004READ\020\001\022\n\n\006UPDATE\020\002\022\n" +
      "\n\006DELETE\020\003\"V\n\030SmartHomeCommandResponse\022\025" +
      "\n\rcorrelationid\030\001 \002(\t\022\016\n\006status\030\002 \002(\t\022\023\n" +
      "\013description\030\003 \001(\t"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_gmagnotta_smarthome_model_event_SmartHomeCommandRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_gmagnotta_smarthome_model_event_SmartHomeCommandRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_gmagnotta_smarthome_model_event_SmartHomeCommandRequest_descriptor,
        new java.lang.String[] { "Id", "Replyto", "Realm", "Operation", "Resource", "Type", "Value", });
    internal_static_org_gmagnotta_smarthome_model_event_SmartHomeCommandResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_gmagnotta_smarthome_model_event_SmartHomeCommandResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_gmagnotta_smarthome_model_event_SmartHomeCommandResponse_descriptor,
        new java.lang.String[] { "Correlationid", "Status", "Description", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
