// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smarthomeevent.proto

package org.gmagnotta.smarthome.model.event;

public final class Smarthomeevent {
  private Smarthomeevent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SmartHomeEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.gmagnotta.smarthome.model.event.SmartHomeEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string realm = 1;</code>
     * @return Whether the realm field is set.
     */
    boolean hasRealm();
    /**
     * <code>required string realm = 1;</code>
     * @return The realm.
     */
    java.lang.String getRealm();
    /**
     * <code>required string realm = 1;</code>
     * @return The bytes for realm.
     */
    com.google.protobuf.ByteString
        getRealmBytes();

    /**
     * <code>required string item = 2;</code>
     * @return Whether the item field is set.
     */
    boolean hasItem();
    /**
     * <code>required string item = 2;</code>
     * @return The item.
     */
    java.lang.String getItem();
    /**
     * <code>required string item = 2;</code>
     * @return The bytes for item.
     */
    com.google.protobuf.ByteString
        getItemBytes();

    /**
     * <code>required string type = 3;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>required string type = 3;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <code>required string type = 3;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>required string value = 4;</code>
     * @return Whether the value field is set.
     */
    boolean hasValue();
    /**
     * <code>required string value = 4;</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>required string value = 4;</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code org.gmagnotta.smarthome.model.event.SmartHomeEvent}
   */
  public static final class SmartHomeEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.gmagnotta.smarthome.model.event.SmartHomeEvent)
      SmartHomeEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SmartHomeEvent.newBuilder() to construct.
    private SmartHomeEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SmartHomeEvent() {
      realm_ = "";
      item_ = "";
      type_ = "";
      value_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SmartHomeEvent();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SmartHomeEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              realm_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              item_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              type_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              value_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.gmagnotta.smarthome.model.event.Smarthomeevent.internal_static_org_gmagnotta_smarthome_model_event_SmartHomeEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.gmagnotta.smarthome.model.event.Smarthomeevent.internal_static_org_gmagnotta_smarthome_model_event_SmartHomeEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent.class, org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent.Builder.class);
    }

    private int bitField0_;
    public static final int REALM_FIELD_NUMBER = 1;
    private volatile java.lang.Object realm_;
    /**
     * <code>required string realm = 1;</code>
     * @return Whether the realm field is set.
     */
    @java.lang.Override
    public boolean hasRealm() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string realm = 1;</code>
     * @return The realm.
     */
    @java.lang.Override
    public java.lang.String getRealm() {
      java.lang.Object ref = realm_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          realm_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string realm = 1;</code>
     * @return The bytes for realm.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRealmBytes() {
      java.lang.Object ref = realm_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        realm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ITEM_FIELD_NUMBER = 2;
    private volatile java.lang.Object item_;
    /**
     * <code>required string item = 2;</code>
     * @return Whether the item field is set.
     */
    @java.lang.Override
    public boolean hasItem() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string item = 2;</code>
     * @return The item.
     */
    @java.lang.Override
    public java.lang.String getItem() {
      java.lang.Object ref = item_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          item_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string item = 2;</code>
     * @return The bytes for item.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getItemBytes() {
      java.lang.Object ref = item_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        item_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private volatile java.lang.Object type_;
    /**
     * <code>required string type = 3;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string type = 3;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 3;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 4;
    private volatile java.lang.Object value_;
    /**
     * <code>required string value = 4;</code>
     * @return Whether the value field is set.
     */
    @java.lang.Override
    public boolean hasValue() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required string value = 4;</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string value = 4;</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRealm()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasItem()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, realm_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, item_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, type_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, realm_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, item_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, type_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent)) {
        return super.equals(obj);
      }
      org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent other = (org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent) obj;

      if (hasRealm() != other.hasRealm()) return false;
      if (hasRealm()) {
        if (!getRealm()
            .equals(other.getRealm())) return false;
      }
      if (hasItem() != other.hasItem()) return false;
      if (hasItem()) {
        if (!getItem()
            .equals(other.getItem())) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (!getType()
            .equals(other.getType())) return false;
      }
      if (hasValue() != other.hasValue()) return false;
      if (hasValue()) {
        if (!getValue()
            .equals(other.getValue())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRealm()) {
        hash = (37 * hash) + REALM_FIELD_NUMBER;
        hash = (53 * hash) + getRealm().hashCode();
      }
      if (hasItem()) {
        hash = (37 * hash) + ITEM_FIELD_NUMBER;
        hash = (53 * hash) + getItem().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
      }
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.gmagnotta.smarthome.model.event.SmartHomeEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.gmagnotta.smarthome.model.event.SmartHomeEvent)
        org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.gmagnotta.smarthome.model.event.Smarthomeevent.internal_static_org_gmagnotta_smarthome_model_event_SmartHomeEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.gmagnotta.smarthome.model.event.Smarthomeevent.internal_static_org_gmagnotta_smarthome_model_event_SmartHomeEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent.class, org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent.Builder.class);
      }

      // Construct using org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        realm_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        item_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.gmagnotta.smarthome.model.event.Smarthomeevent.internal_static_org_gmagnotta_smarthome_model_event_SmartHomeEvent_descriptor;
      }

      @java.lang.Override
      public org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent getDefaultInstanceForType() {
        return org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent.getDefaultInstance();
      }

      @java.lang.Override
      public org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent build() {
        org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent buildPartial() {
        org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent result = new org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.realm_ = realm_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.item_ = item_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent) {
          return mergeFrom((org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent other) {
        if (other == org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent.getDefaultInstance()) return this;
        if (other.hasRealm()) {
          bitField0_ |= 0x00000001;
          realm_ = other.realm_;
          onChanged();
        }
        if (other.hasItem()) {
          bitField0_ |= 0x00000002;
          item_ = other.item_;
          onChanged();
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000004;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000008;
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasRealm()) {
          return false;
        }
        if (!hasItem()) {
          return false;
        }
        if (!hasType()) {
          return false;
        }
        if (!hasValue()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object realm_ = "";
      /**
       * <code>required string realm = 1;</code>
       * @return Whether the realm field is set.
       */
      public boolean hasRealm() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string realm = 1;</code>
       * @return The realm.
       */
      public java.lang.String getRealm() {
        java.lang.Object ref = realm_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            realm_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string realm = 1;</code>
       * @return The bytes for realm.
       */
      public com.google.protobuf.ByteString
          getRealmBytes() {
        java.lang.Object ref = realm_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          realm_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string realm = 1;</code>
       * @param value The realm to set.
       * @return This builder for chaining.
       */
      public Builder setRealm(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        realm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string realm = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRealm() {
        bitField0_ = (bitField0_ & ~0x00000001);
        realm_ = getDefaultInstance().getRealm();
        onChanged();
        return this;
      }
      /**
       * <code>required string realm = 1;</code>
       * @param value The bytes for realm to set.
       * @return This builder for chaining.
       */
      public Builder setRealmBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        realm_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object item_ = "";
      /**
       * <code>required string item = 2;</code>
       * @return Whether the item field is set.
       */
      public boolean hasItem() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string item = 2;</code>
       * @return The item.
       */
      public java.lang.String getItem() {
        java.lang.Object ref = item_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            item_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string item = 2;</code>
       * @return The bytes for item.
       */
      public com.google.protobuf.ByteString
          getItemBytes() {
        java.lang.Object ref = item_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          item_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string item = 2;</code>
       * @param value The item to set.
       * @return This builder for chaining.
       */
      public Builder setItem(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        item_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string item = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearItem() {
        bitField0_ = (bitField0_ & ~0x00000002);
        item_ = getDefaultInstance().getItem();
        onChanged();
        return this;
      }
      /**
       * <code>required string item = 2;</code>
       * @param value The bytes for item to set.
       * @return This builder for chaining.
       */
      public Builder setItemBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        item_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 3;</code>
       * @return Whether the type field is set.
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required string type = 3;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 3;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 3;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 3;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>required string value = 4;</code>
       * @return Whether the value field is set.
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required string value = 4;</code>
       * @return The value.
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string value = 4;</code>
       * @return The bytes for value.
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string value = 4;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000008);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>required string value = 4;</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        value_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.gmagnotta.smarthome.model.event.SmartHomeEvent)
    }

    // @@protoc_insertion_point(class_scope:org.gmagnotta.smarthome.model.event.SmartHomeEvent)
    private static final org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent();
    }

    public static org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SmartHomeEvent>
        PARSER = new com.google.protobuf.AbstractParser<SmartHomeEvent>() {
      @java.lang.Override
      public SmartHomeEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SmartHomeEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SmartHomeEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SmartHomeEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.gmagnotta.smarthome.model.event.Smarthomeevent.SmartHomeEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_gmagnotta_smarthome_model_event_SmartHomeEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_gmagnotta_smarthome_model_event_SmartHomeEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024smarthomeevent.proto\022#org.gmagnotta.sm" +
      "arthome.model.event\"J\n\016SmartHomeEvent\022\r\n" +
      "\005realm\030\001 \002(\t\022\014\n\004item\030\002 \002(\t\022\014\n\004type\030\003 \002(\t" +
      "\022\r\n\005value\030\004 \002(\t"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_gmagnotta_smarthome_model_event_SmartHomeEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_gmagnotta_smarthome_model_event_SmartHomeEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_gmagnotta_smarthome_model_event_SmartHomeEvent_descriptor,
        new java.lang.String[] { "Realm", "Item", "Type", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
